# Generated by Django 3.0.4 on 2020-03-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secton', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='people_count',
            field=models.IntegerField(default=0),
        ),
    ]
